import type { LucideIcon } from "lucide-react";
import {
  Archive,
  AudioLines,
  BarChart3,
  Calendar,
  Camera,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Combine,
  Copy,
  Cpu,
  Database,
  Disc3,
  Download,
  Eraser,
  File,
  FileAudio,
  FileImage,
  FileSearch,
  FileText,
  FileVideo,
  Files,
  Film,
  Folder,
  FolderPen,
  FolderSearch,
  Gauge,
  Globe,
  HardDrive,
  Hash,
  History,
  Image,
  Inbox,
  Languages,
  Layers,
  Link,
  ListChecks,
  Lock,
  Mail,
  Monitor,
  Music,
  Palette,
  PenLine,
  Play,
  Puzzle,
  Scissors,
  Search,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Star,
  Table,
  Tag,
  Trash2,
  Upload,
  Video,
  WandSparkles,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Icon names a mod can put in `icon = "..."` (lucide names, kebab-case). Keep in step with
 * `ICON_NAMES` in core/mods/manifest.py (a test compares them); unknown names show a puzzle piece.
 */
const MOD_ICONS: Record<string, LucideIcon> = {
  archive: Archive,
  "audio-lines": AudioLines,
  "bar-chart-3": BarChart3,
  calendar: Calendar,
  camera: Camera,
  "clipboard-list": ClipboardList,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  combine: Combine,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  "disc-3": Disc3,
  download: Download,
  eraser: Eraser,
  file: File,
  "file-audio": FileAudio,
  "file-image": FileImage,
  "file-search": FileSearch,
  "file-text": FileText,
  "file-video": FileVideo,
  files: Files,
  film: Film,
  folder: Folder,
  "folder-pen": FolderPen,
  "folder-search": FolderSearch,
  gauge: Gauge,
  globe: Globe,
  "hard-drive": HardDrive,
  hash: Hash,
  history: History,
  image: Image,
  inbox: Inbox,
  languages: Languages,
  layers: Layers,
  link: Link,
  "list-checks": ListChecks,
  lock: Lock,
  mail: Mail,
  monitor: Monitor,
  music: Music,
  palette: Palette,
  "pen-line": PenLine,
  play: Play,
  puzzle: Puzzle,
  scissors: Scissors,
  search: Search,
  settings: Settings,
  shield: Shield,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  table: Table,
  tag: Tag,
  "trash-2": Trash2,
  upload: Upload,
  video: Video,
  "wand-sparkles": WandSparkles,
  wrench: Wrench,
  zap: Zap,
};

export function modIcon(name: string): LucideIcon {
  return MOD_ICONS[name] ?? Puzzle;
}
